### ISSUE TITLE
Update django to 4.2

### ISSUE THREAD

**Issue by tymees** [UiL-OTS-labs/babex#193]
Currently the django version is pinned to 4.0, which has been EOL for a couple of months already. 

I'd suggest updating to the latest LTS, 4.2. (5.0 if you're feeling advanterous, but that's more work. Updating to 4.2 should be relatively easy).

**Comment by bbonf** [comment]
Seems like shared-core (develop) isn't fully compatible with 4.2
https://github.com/UiL-OTS-labs/babex/actions/runs/8554149815/job/23438859526?pr=194#step:9:78
